swagger: "2.0"
info:
  title: Kubernetes Operational View
  version: "1.0"
produces:
  - application/json
paths:
  /kubernetes-clusters:
   get:
    summary: Get Kubernetes clusters
    operationId: app.get_clusters
    responses:
      "200":
        description: List of Kubernetes clusters
        schema:
          type: object
          properties:
            kubernetes_clusters:
              type: object
              properties:
                api_server_url:
                  type: string
